spring.application.name=mychat
spring.datasource.url=jdbc:postgresql://localhost:5432/mychat
spring.datasource.username=mychat_user
spring.datasource.password=mychat_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
